### ISSUE TITLE
Incomplete code 

### ISSUE THREAD

**Issue by chetna510** [MunibaFaiza/Free_Energy_Landscape-MD#1]
The jupyter notebook provided is unable to generate the respective frames of the minima points. Moreover, no file named as minima_time_frames.txt is generated.

**Comment by MunibaFaiza** [comment]
You must be doing something wrong. Ensure that you have calculated the eigenvectors and eigenvalues and Gibb's Free Energy correctly. Further, read the following article carefully, you must be missing out on something.

https://bioinformaticsreview.com/20240228/free_energy_landscape-md-python-package-to-create-free-energy-landscape-using-pca-from-gromacs/

Closing this issue now as it has been tested with multiple datasets and found to be functioning properly.

**Comment by chetna510** [comment]
In the repository, the file minima_with_frames.txt does not contains the time frame. It does not have any value and it only contains the minima points. Kindly resolve my query. 
![Screenshot 2024-04-29 172704](https://github.com/MunibaFaiza/Free_Energy_Landscape-MD/assets/168427361/944aeb8b-2b78-4f81-a3ba-e81472ca3476)

**Comment by MunibaFaiza** [comment]
I used a small MD (1ns) just for demonstration purposes here. However, it generates many minima points for a long simulation. As I said, you can just read the article for details. Everything is explained in the article.
