### ISSUE TITLE
frames for the minima is not generated

### ISSUE THREAD

**Issue by sherifelsabbagh** [MunibaFaiza/Free_Energy_Landscape-MD#3]
Hi

I tried your code and it runs fine generating a 3D plot. However, the frames corresponding to the minima are not generated. The command gives and empty list and a text file is not generated. 
I tried this using my files for a 100 ns simulation and also tried your files. so better adjust the code because the important step which is identifying the minima frames is not working..

**Comment by MunibaFaiza** [comment]
Read the following article carefully. 
https://bioinformaticsreview.com/20240228/free_energy_landscape-md-python-package-to-create-free-energy-landscape-using-pca-from-gromacs/

**Comment by sherifelsabbagh** [comment]
why should I pay 26 dollars to read the article to solve this issue ?

Thanks :)
